/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println("¡Hola, Kotlin!")
    data()
    mostrarTiposDeDatos()
    calcularAreaRectangulo(305.2, 25.1)
    val numero: Int = 24
    if (esPar(numero)) {
        println("$numero es par")
    } else {
        println("$numero es impar")
    }
    val signo: String = signo(numero)
    println("$numero es $signo")
}

fun data() {
    val nombre = "Ivo" 
    val fecha = "22/04/2025" 
    println("nombre: ${nombre}")
    println("fecha: ${fecha}")
}

fun mostrarTiposDeDatos() {
    val cadena: String = "Esto es una cadena"
    val entero: Int = 25
    val decimal: Double = 1.75
    val booleano: Boolean = true
    
    println("String: $cadena")
    println("int: $entero")
    println("double: $decimal")
    println("booleano: $booleano")
}

fun calcularAreaRectangulo(base: Double, altura: Double){
    val area = base * altura 
    println("Area: $area")
}

fun esPar(numero: Int): Boolean {
    return when {
        numero % 2 == 0 -> true
        else -> false
    }
}

fun signo(numero: Int): String{
    return when{
        numero < 0 -> "Negativo"
        numero > 0 -> "Positivo"
        else -> "Cero"
    }
}